package test.java.login;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class LoginKOPasswordTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		//System.setProperty("webdriver.gecko.driver", "drivers/geckodriver");
		FirefoxOptions firefoxOptions = new FirefoxOptions();
		firefoxOptions.setHeadless(true);
		driver = new FirefoxDriver(firefoxOptions);
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void loginKOPassword() throws InterruptedException {
		driver.get("https://damp-tor-38829.herokuapp.com/login");
		driver.manage().window().setSize(new Dimension(1366, 741));
		driver.findElement(By.xpath("//input[@type='email']")).click();
		driver.findElement(By.cssSelector(".ajax-button")).click();
		{
			List<WebElement> elements = driver
					.findElements(By.xpath("//input[@type='email' and @class='form-control is-invalid']"));
			assert (elements.size() > 0);
		}
		driver.findElement(By.xpath("//input[@type='email']")).sendKeys("user02@mail.com");
		driver.findElement(By.xpath("//input[@type='password']")).click();
		driver.findElement(By.xpath("//input[@type='password']")).sendKeys("1234");
		driver.findElement(By.cssSelector(".ajax-button")).click();
		
		assertThat(driver.findElement(By.xpath("//div[@parasails-component='cloud-error']")).getText(), is(
				"The credentials you entered are not associated with an account. Please check your email and/or password and try again."));
		WebElement element = driver.findElement(By.cssSelector(".ajax-button"));
			assert element.isDisplayed();
		
	}
}
